recipes:
    global:
        - dotfiles::gitconfig
        - dotfiles::vim
        - applications::mysql
        - applications::php56
        - applications::skylab
    mac_os_x:
        - applications::sublime_text_3
        - applications::gnu-tar
        - osxdefaults::set_terminal_profile
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::disable_disk_image_verification
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::finder_unhide_home
attributes:
    mysql_root_password: "password"
    homebrewalt:
        apps:
            - git
            - git-extras
            - wget
            - pwgen
            - xmlstarlet
            - htop-osx
            - siege
            - watch
            - rsync
        cask_apps:
            - imageoptim
            - phpstorm
            - sequel-pro
    nodejs:
        apps:
            - uglify-js
            - uglifycss
            - bower
            - gulp
    php-apps:
        - composer
